### ISSUE TITLE
"Strong wind" translation broken

### ISSUE THREAD

**Issue by ls6** [darkskyapp/forecast-io-translations#59] opened 2015-12-22 08:43 UTC
The term "breezy" does not mean "light wind" (http://www.merriam-webster.com/dictionary/breezy), rather the opposite.
I'm not picky about language but have noticed that in translation (at least to Polish) it actually gets translated that way which kind of defeats the purpose. The forecast says "light wind" in Polish and we get branches falling down.
The problem does not reside in the Polish translation, though. There's no "breezy" in any place of the Polish translation and as I'm not sure how the whole process goes I've decided to report it here.

Or I had it wrong and the simply the wind prediction is off for my neck of woods?

**Comment by ironwallaby** [comment] 2015-12-22 14:23
Breezy *does* mean "having a light or gentle wind." Having grown up in America, I can confirm this first-hand. :)

*   http://www.merriam-webster.com/dictionary/breeze
*   https://en.wiktionary.org/wiki/breeze#Noun_2
*   https://www.wordnik.com/words/breeze
*   http://dictionary.reference.com/browse/breeze
*   http://www.oxforddictionaries.com/definition/english/breeze

Anyway, as for Polish, it looks like "breezy" has been translated as "słaby wiatr":

    https://github.com/darkskyapp/forecast-io-translations/blob/master/lib/lang/pl.js#L57

I have no idea if that's a good translation or not, but if it doesn't have the sense of "a light wind" then it's definitely wrong :)

**Comment by ls6** [comment] 2015-12-22 14:58
Apparently there is a difference between "breeze" and "breezy" (see both in M-W) but I'm not going to argue with a native speaker -- I guess most people will interpret it your way :)
If we accept breezy = breeze then the Polish translation is fine and the forecast.io wind prediction is poor. For the last month we had twice warning about hmmm... "gusty" wind and on both occasions the forecast.io said "breezy".

**Comment by ironwallaby** [comment] 2015-12-22 15:12
OK. I'll make a note of that—the issue is probably that we don't have high resolution data for much of mainland Europe yet, and since wind is a high resolution phenomenon, our predictions are poor. We're working on integrating some new data models, which should fix this, but it'll probably be some months before it goes live.

But since it's not an issue with the translations module, I'll close this ticket. Thanks! :)

**Closed by ironwallaby** 2015-12-22 15:12 UTC
